### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by x11tete11x** [UnitedRPMs/handbrake#4]
Fresh Fedora 24 + UnitedRPMS + Nvidia driver from your repos

I'm just testing what you offer :D, this time Handbrake, looks like it have troubles with h264

Log:
http://pastebin.com/0C1aB8vg

Video Settings:

http://i.imgur.com/4xbzz3H.png

thx!

**Comment by paulcarroty** [comment]
10bit video support need a rebuild x264 with flag `--bit-depth=10` and it's break 8bit support: http://video.stackexchange.com/questions/13164/encoding-422-in-10-bit-with-libx264

Please do not use the main profile.

**Comment by x11tete11x** [comment]
Thx! 
I'm thinking about new people that happens this too (or people that might use 10 bit depth encoding), perhaps there is a way to bring full support looks like negativo17 got it http://negativo17.org/support-for-81012-bit-color-depths-in-handbrake/ 

or the other aproach might be disable 10bit support in Handbrake (if that is possible with something like --disable10bit (i dont look the Handbrake source code) )

Thx for your work!
